# Reagent Configuration
# Spells: fire, bolt, storm, timebomb, teleport, teleportspawn, heal,
#         arrowstorm, stonewall, firewall, skeleton, zombie, timetravel,
#         megabolt, scan, tree
#
# Info: https://github.com/pr0f1x/reagent

# Broadcast to all players when someone casts a spell.
broadcast: true

# Give players hints on what materials they are missing.
hint: true

# Allow players to cast spells with the command line.
command: false

# Allow players to cast spells with an item.
item: book

# List of spells. Configure each spells cost.
spells:
  tree:
    cooldown: 60
    materials:
      bone: 1
      sapling: 1
  scan:
    cooldown: 60
    materials:
      redstone: 5
      obsidian: 1
  megabolt:
    cooldown: 60
    materials:
      redstone: 20
      glass: 5
  fire:
    cooldown: 5
    materials:
      wood: 10
      flint: 2
      coal: 1
  bolt:
    cooldown: 5
    materials:
      redstone: 10
      glass: 1
  storm:
    cooldown: 5
    materials:
      diamond: 1
      water_bucket: 1
      redstone: 5
  timebomb:
    cooldown: 30
    materials:
      redstone: 10
      coal: 20
      flint: 5
  teleport:
    cooldown: 5
    materials:
      redstone: 8
  teleportspawn:
    cooldown: 30
    materials:
      compass: 1
      redstone: 5
  heal:
    cooldown: 30
    materials:
      redstone: 10
  arrowstorm:
    cooldown: 20
    materials:
      wood: 5
      feather: 1
      flint: 1
  stonewall:
    cooldown: 30
    materials:
      stone: 20
      redstone: 5
  skeleton:
    cooldown: 60
    materials:
      bone: 20
      obsidian: 1
  zombie:
    cooldown: 60
    materials:
      pork: 20
      obsidian: 1
  firewall:
    cooldown: 30
    materials:
      wood: 10
      coal: 10
      flint: 1
  timetravel:
    cooldown: 60
    materials:
      watch: 1
      diamond: 5
      redstone: 5