name: Reagent
main: net.hpxn.reagent.ReagentPlugin
version: 0.4
author: pr0f1x
commands:
  reagent:
    description: Reagent spell casting.
    usage: |
           /<command> <spell> - initializes the chosen spell.